services:
  app:
    restart: always
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: php_prod
    environment:
        - APP_ENV=${APP_ENV:-prod}
        - DATABASE_URL=${DATABASE_URL}
        - PAYUM_CYPHER_KEY=${PAYUM_CYPHER_KEY}
        - TPAY_CLIENT_ID=${TPAY_CLIENT_ID}
        - TPAY_CLIENT_SECRET=${TPAY_CLIENT_SECRET}
        - TPAY_CARDS_API=${TPAY_CARDS_API}
        - TPAY_NOTIFICATION_SECURITY_CODE=${TPAY_NOTIFICATION_SECURITY_CODE}
        - TPAY_MERCHANT_ID=${TPAY_MERCHANT_ID}
        - TPAY_GOOGLE_MERCHANT_ID=${TPAY_GOOGLE_MERCHANT_ID}
        - TPAY_APPLE_PAY_MERCHANT_ID=${TPAY_APPLE_PAY_MERCHANT_ID}
        - TPAY_PBL_CHANNEL_ID=${TPAY_PBL_CHANNEL_ID}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: cw_rocks
    volumes:
      - database:/var/lib/mysql

volumes:
  caddy_data:
  caddy_config:
  database:
