services:
  app:
    restart: always
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: php_prod
    environment:
        - APP_ENV=${APP_ENV:-prod}
        - DATABASE_URL=mysql://root:cw_rocks@db/cw_sylius_tpay_plugin_%kernel.environment%?serverVersion=mariadb-10.11.0
        - PAYUM_CYPHER_KEY=${PAYUM_CYPHER_KEY}
        - TPAY_CLIENT_ID=${TPAY_CLIENT_ID}
        - TPAY_CLIENT_SECRET=${TPAY_CLIENT_SECRET}
        - TPAY_CARDS_API=${TPAY_CARDS_API}
        - TPAY_NOTIFICATION_SECURITY_CODE=${TPAY_NOTIFICATION_SECURITY_CODE}
        - TPAY_MERCHANT_ID=${TPAY_MERCHANT_ID}
        - TPAY_GOOGLE_MERCHANT_ID=${TPAY_GOOGLE_MERCHANT_ID}
        - TPAY_APPLE_PAY_MERCHANT_ID=${TPAY_APPLE_PAY_MERCHANT_ID}
        - TPAY_PBL_CHANNEL_ID=${TPAY_PBL_CHANNEL_ID}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:10.11
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      MARIADB_ROOT_PASSWORD: cw_rocks
    volumes:
      - database:/var/lib/mysql

volumes:
  caddy_data:
  caddy_config:
  database:
