'%commerce_weavers_sylius_tpay.model.credit_card.class%':
    collectionOperations:
        shop_get:
            method: 'GET'
            path: /shop/credit-cards
            normalization_context:
                groups:
                    - 'commerce_weavers_sylius_tpay:shop:credit_card:index'
    itemOperations:
        shop_get:
            method: 'GET'
            path: /shop/credit-cards/{id}
            normalization_context:
                groups:
                    - 'commerce_weavers_sylius_tpay:shop:credit_card:show'
        shop_delete:
            method: 'DELETE'
            path: /shop/credit-cards/{id}
    properties:
        id:
            identifier: true
        tail:
            writable: false
        brand:
            writable: false
