'%sylius.model.order.class%':
    itemOperations:
        shop_pay:
            method: 'POST'
            path: '/shop/orders/{tokenValue}/pay'
            messenger: 'input'
            input: 'CommerceWeavers\SyliusTpayPlugin\Api\Command\Pay'
            status: 200
            denormalization_context:
                groups:
                    - 'commerce_weavers_tpay:shop:order:pay'
            normalization_context:
                groups:
                    - 'commerce_weavers_tpay:shop:order:pay_result'
            openapi_context:
                summary: 'Pay for the order'
