CommerceWeavers\SyliusTpayPlugin\Api\Resource\TpayBank:
    collectionOperations:
        get: ~
    itemOperations:
        get: ~
        properties:
            id:
                identifier: true
