sylius_grid:
    grids:
        commerce_weavers_sylius_tpay_shop_account_credit_card:
            driver:
                name: doctrine/orm
                options:
                    class: "%commerce_weavers_sylius_tpay.model.credit_card.class%"
                    repository:
                        method: createByCustomerListQueryBuilder
                        arguments:
                            - "expr:service('sylius.context.customer').getCustomer()"
                            - "expr:service('sylius.context.channel').getChannel()"
            sorting:
                expirationDate: desc
            fields:
                brand:
                    type: string
                    label: commerce_weavers_sylius_tpay.shop.credit_card.brand
                    sortable: ~
                tail:
                    type: string
                    label: commerce_weavers_sylius_tpay.shop.credit_card.tail
                    sortable: ~
                expirationDate:
                    type: datetime
                    label: commerce_weavers_sylius_tpay.shop.credit_card.expiration_date
                    sortable: ~
                    options:
                        format: m-Y
            actions:
                item:
                    delete:
                        type: delete
                        label: sylius.ui.delete
                        options:
                            link:
                                route: !php/const CommerceWeavers\SyliusTpayPlugin\Routing::SHOP_ACCOUNT_CREDIT_CARD_DELETE
                                parameters:
                                    id: resource.id
