name: Continuous Integration

on:
    workflow_dispatch: ~
    workflow_call:
        inputs:
            type:
                description: "Type of the build"
                required: true
                type: string

jobs:
    get-matrix:
        runs-on: ubuntu-latest
        name: "Get matrix"
        outputs:
            matrix: ${{ steps.matrix.outputs.prop }}
        steps:
            -   name: "Checkout"
                uses: actions/checkout@v4

            -
                name: "Get matrix"
                id: matrix
                uses: notiz-dev/github-action-json-property@release
                with:
                    path: '.github/workflows/_matrix.json'
                    prop_path: '${{ inputs.type }}.ci'

    tests:
        needs: get-matrix
        
        runs-on: ubuntu-latest

        name: "Sylius ${{ matrix.sylius }}, PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}, MySQL ${{ matrix.mysql }}"

        strategy:
            fail-fast: false
            matrix: ${{ fromJson(needs.get-matrix.outputs.matrix) }}

        env:
            APP_ENV: test
            DATABASE_URL: "mysql://root:root@127.0.0.1/sylius?serverVersion=${{ matrix.mysql }}"

        steps:
            -
                uses: actions/checkout@v3

            -   name: Build application
                uses: SyliusLabs/BuildTestAppAction@v2.1
                with:
                    build_type: "plugin"
                    cache_key: "${{ github.run_id }}-${{ runner.os }}-${{ hashFiles('composer.json') }}-sylius-${{ matrix.sylius }}-symfony-${{ matrix.symfony }}"
                    cache_restore_key: "${{ github.run_id }}-${{ runner.os }}-${{ hashFiles('composer.json') }}-sylius-${{ matrix.sylius }}-symfony-${{ matrix.symfony }}"
                    database_version: ${{ matrix.mysql }}
                    php_version: ${{ matrix.php }}
                    symfony_version: ${{ matrix.symfony }}
                    sylius_version: ${{ matrix.sylius }}
                    e2e_js: true

            -   name: Check dependencies
                continue-on-error: true
                run: vendor/bin/composer-dependency-analyser

            -   name: Static analysis
                run: vendor/bin/phpstan

            -   name: Check coding standard
                run: vendor/bin/ecs check

            -   name: Run tests
                run: vendor/bin/phpunit
